{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plinto.fullname" . }}-api
  labels:
    {{- include "plinto.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "plinto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plinto.fullname" . }}-admin
  labels:
    {{- include "plinto.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "plinto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plinto.fullname" . }}-dashboard
  labels:
    {{- include "plinto.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "plinto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dashboard
{{- end }}