apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plinto.fullname" . }}-secret
  labels:
    {{- include "plinto.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "plinto.databaseUrl" . | b64enc | quote }}
  redis-url: {{ include "plinto.redisUrl" . | b64enc | quote }}
  jwt-secret-key: {{ .Values.api.env.JWT_SECRET_KEY | b64enc | quote }}
  {{- if .Values.backup.enabled }}
  backup-access-key: {{ .Values.backup.storage.accessKey | b64enc | quote }}
  backup-secret-key: {{ .Values.backup.storage.secretKey | b64enc | quote }}
  {{- end }}